version: '3.8'

networks:
  loki-grafana:
    driver: bridge

volumes:
  loki_data: {} # Volume để lưu trữ dữ liệu của Loki
  grafana_data: {} # Volume để lưu trữ dữ liệu của Grafana
  promtail_positions: {} # Volume để Promtail lưu trạng thái đọc log

services:
  node-log-producer: # Dịch vụ Node.js để tạo log
    build: ./node-file-log
    container_name: node-log-producer-v2
    # Nếu ứng dụng Node.js của bạn cần cổng để lắng nghe (ví dụ một API để nhận log), hãy thêm vào đây:
    ports:
      - "3250:3250"
    volumes:
      # RẤT QUAN TRỌNG: Mount thư mục logs trên host vào container Node.js
      # Đảm bảo ứng dụng Node.js của bạn ghi file modsec_audit.json vào /app/logs/modsec_audit.json
      - ./logs:/logs # Mount thư mục 'logs' từ host vào '/app/logs' trong container Node.js
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    networks:
      - loki-grafana

  loki:
    image: grafana/loki:2.9.2
    container_name: loki-v2
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki # Nơi Loki lưu trữ dữ liệu (chunks, index)
      # Mount file cấu hình Loki từ đường dẫn bạn cung cấp
      - ./monitoring/loki_data/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-grafana
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail-v2
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yaml:ro
      # Promtail chỉ đọc log ModSecurity (từ Node.js) từ thư mục 'logs' được mount từ host
      - ./logs:/var/log/modsec:ro # Promtail sẽ đọc modsec_audit.json từ đây
      # Đã XÓA: Không còn mount /var/log/nginx nữa vì không có log Nginx
      # Mount volume cho file positions.yaml để Promtail lưu trạng thái đọc log
      - promtail_positions:/tmp/promtail_data:rw
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki-grafana
    depends_on:
      - loki
    restart: unless-stopped # Đảm bảo Promtail luôn chạy lại nếu bị lỗi
    # Cần set timezone cho Promtail để nó xử lý timestamp nhất quán
    environment:
      - TZ=Asia/Ho_Chi_Minh 

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana-v2
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Đặt mật khẩu admin cho Grafana
      - TZ=Asia/Ho_Chi_Minh # Đảm bảo Grafana hiển thị thời gian đúng múi giờ
    networks:
      - loki-grafana # Lưu trữ dashboard và datasource
    depends_on:
      - loki
    restart: unless-stopped