services:
  nginx-modsec:
    build: .
    container_name: nginx-modsec
    ports:
      - "5353:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./modsecurity.conf:/usr/local/nginx/conf/modsecurity.conf:ro
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./unicode.mapping:/usr/local/nginx/conf/unicode.mapping:ro
      - ./logs:/var/log/modsec
    restart: unless-stopped
  nodejs-modsec:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: nodejs-mod-security
    ports:
      - "30000:30000"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./logs:/app/build/logs
    restart: unless-stopped
    env_file:
      - .env
