# Build phase
FROM node:20 AS builder

WORKDIR /app

COPY package.json ./
RUN yarn install --production

COPY tsconfig.json ./
COPY src ./src
RUN yarn build

# Runtime phase
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build

CMD ["node", "build/index.js"]