# monitoring/promtail-config.yaml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail_data/positions.yaml # Đảm bảo thư mục /tmp/promtail_data tồn tại bên trong container

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki is accessible via its service name 'loki' within the Docker network

scrape_configs:
  # Chỉ còn cấu hình cho modsecurity_audit_log
  - job_name: modsecurity_audit_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: modsecurity_audit_log
          instance: node-log-producer-01 # Có thể đổi instance name cho phù hợp với Node.js project
          __path__: /var/log/modsec/modsec_log.json # Promtail sẽ đọc từ file này trong mount volume
    pipeline_stages:
      - json:
          expressions:
            # transaction_id: transaction.unique_id
            remote_addr: transaction.client_ip
            server_id: transaction.server_id
            client_port: transaction.client_port
            host_ip: transaction.host_ip
            host_port: transaction.host_port
            request_method: transaction.request.method
            # http_version: transaction.request.http_version
            hostname: transaction.request.hostname
            request_uri: transaction.request.uri
            response_http_code: transaction.response.http_code
            # response_content_length: transaction.response.headers."Content-Length"
            # response_content_type: transaction.response.headers."Content-Type"
            # modsecurity_version: transaction.producer.modsecurity
            # connector: transaction.producer.connector
            # secrules_engine: transaction.producer.secrules_engine
            first_message_detail: transaction.messages[0].message
            first_message_match: transaction.messages[0].details.match
            first_message_rule_id: transaction.messages[0].details.ruleId
            first_message_file: transaction.messages[0].details.file
            # first_message_line_number: transaction.messages[0].details.lineNumber
            first_message_data: transaction.messages[0].details.data
            # first_message_severity: transaction.messages[0].details.severity
            modsec_timestamp: transaction.time_stamp
      - timestamp:
          source: modsec_timestamp
          format: "02/Jan/2006:15:04:05 -0700"
      - labels:
          job:
          instance:
          hostname:
          # transaction_id:
          remote_addr:
          request_method:
          request_uri:
          response_http_code:
          # modsecurity_version:
          first_message_rule_id:
          first_message_detail:
          first_message_match:
          first_message_data:
  - job_name: system_metrics_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_metrics_log
          instance: system_metrics-01 
          __path__: /var/log/modsec/system_metrics.json
    pipeline_stages:
      # Bước 1: Trích xuất các trường từ JSON
      - json:
          expressions:
            name_server: "name_server"
            cpu_info_str: "cpu_info"
            active_ram_str: "active_ram"
            free_ram_str: "free_ram"
            total_ram_str: "total_ram"
            avg_latency_str: "avg_latency"
            cpu_info_total_ram: "cpu_info_total_ram"
            
      # Bước 2: Sử dụng regex để loại bỏ các đơn vị và chỉ giữ lại giá trị số
      - regex:
          source: cpu_info_str
          expression: "(?P<cpu_value>[0-9.]+)"
      - regex:
          source: active_ram_str
          expression: "(?P<active_ram_value>[0-9.]+)"
      - regex:
          source: free_ram_str
          expression: "(?P<free_ram_value>[0-9.]+)"
      - regex:
          source: total_ram_str
          expression: "(?P<total_ram_value>[0-9.]+)"
      - regex:
          source: avg_latency_str
          expression: "(?P<avg_latency_value>[0-9.]+)"

      # Bước 3: Gán các giá trị đã được làm sạch thành labels
      - labels:
          name_server:
          cpu_value:
          active_ram_value:
          free_ram_value:
          total_ram_value:
          avg_latency_value:
          cpu_info_total_ram: